
services:
  - type: web
    name: cricket-team-11
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
